<template>
  <div class="fixed top-0 left-0 w-full h-full flex justify-center items-center">
    <div
      name="backdrop"
      class="w-lvw h-lvh bg-black bg-opacity-50"
      @click="router.push(`/task`)"
    ></div>
    <div
      name="detail"
      class="fixed w-3/5 h-3/5 border p-8 bg-sky-200 flex flex-col indicator rotate-in-center"
    >
      <p>title : <span v-text="taskDetail.title"></span></p>
      <p>desc : <span v-text="taskDetail.description"></span></p>
      <p>assignees : <span v-text="taskDetail.assignees"></span></p>
      <p>status : <span v-text="taskDetail.status"></span></p>
      <p>timezone : <span v-text="timezone"></span></p>
      <p>createOn : <span v-text="taskDetail.createdOn"></span></p>
      <p>updateOn : <span v-text="taskDetail.updatedOn"></span></p>
    </div>
  </div>
</template>

<script setup>
import { onMounted } from 'vue'
import { getTask } from '@/lib/fetchAPI'
import { ref } from 'vue'
import router from '@/router/router'

const taskDetail = ref({})
onMounted(async () => {
  const id = router.currentRoute.value.params.id
  console.log(id)
  try {
    const taskRes = await getTask(`tasks/${id}`)
    taskDetail.value = taskRes.data
    formatDate()
  } catch (error) {
    console.error('Error fetching tasks:', error.message)
  }
})

const timezone = ref(Intl.DateTimeFormat().resolvedOptions().timeZone)
const createDate = ref(null)
const updateDate = ref(null)
function formatDate() {
  const timeformat = {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  }
  console.log(taskDetail.value.createdOn);
  console.log(taskDetail.value.updatedOn);
  createDate.value = Date(taskDetail.value.createdOn).toLocaleString()
  updateDate.value = Date(taskDetail.value.updatedOn).toLocaleString()
  console.log(createDate.value);
  console.log(updateDate.value);
}

const formattedCreateDate = ref(null)
const formattedUpdateDate = ref(null)

onMounted(() => {
  formattedCreateDate.value = createDate.value
  formattedUpdateDate.value = updateDate.value
})
</script>

<style>
.rotate-in-center {
  -webkit-animation: rotate-in-center 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: rotate-in-center 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-4-25 12:42:46
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-in-center
 * ----------------------------------------
 */
@-webkit-keyframes rotate-in-center {
  0% {
    -webkit-transform: rotate(-360deg);
    transform: rotate(-360deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotate(0);
    transform: rotate(0);
    opacity: 1;
  }
}
@keyframes rotate-in-center {
  0% {
    -webkit-transform: rotate(-360deg);
    transform: rotate(-360deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotate(0);
    transform: rotate(0);
    opacity: 1;
  }
}
</style>
